name: Azafea Metabase Documentation
on:
  push:
    branches:
      - master

jobs:
  metabase:
    name: Update Documentation on Metabase
    runs-on: ubuntu-latest
    env:
      METABASE_USERNAME: ${{ secrets.METABASE_USERNAME }}
      METABASE_PASSWORD: ${{ secrets.METABASE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Install GObject-Introspection
        run: apt install libgirepository1.0-dev
      - name: Install Dev Dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install --dev
      - name: Upload Documentation
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run sphinx-build docs/source/ docs/build/html/ -b metabase -E
